//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionLegalite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asesore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asesore()
        {
            this.solicitudes = new HashSet<solicitude>();
            this.subscripcions = new HashSet<subscripcion>();
        }
    
        public int idasesor { get; set; }
        public string nombreusuario { get; set; }
        public string password { get; set; }
        public Nullable<int> nivel { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> salariobasico { get; set; }
        public Nullable<decimal> costodiario { get; set; }
        public Nullable<decimal> costohora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solicitude> solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<subscripcion> subscripcions { get; set; }
    }
}
