//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionLegalite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallesolicitud
    {
        public int iddetalle { get; set; }
        public Nullable<int> idsolicitud { get; set; }
        public string respuestaasesor { get; set; }
        public string mensajecliente { get; set; }
        public string fechahoraactualizacion { get; set; }
    
        public virtual solicitude solicitude { get; set; }
    }
}
