//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionLegalite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public post()
        {
            this.reposts = new HashSet<repost>();
        }
    
        public int id { get; set; }
        public string Titulo { get; set; }
        public string Contenido { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> idcliente { get; set; }
        public Nullable<int> Actividad { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<repost> reposts { get; set; }
        public virtual subscripcion subscripcion { get; set; }
    }
}
