//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionLegalite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitude
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public solicitude()
        {
            this.detallesolicituds = new HashSet<detallesolicitud>();
        }
    
        public int idsolicitud { get; set; }
        public Nullable<int> nitcliente { get; set; }
        public Nullable<int> idasesor { get; set; }
        public string actividad { get; set; }
        public Nullable<System.DateTime> fechaHoraInicio { get; set; }
        public Nullable<System.DateTime> FechaHoraFin { get; set; }
        public string estado { get; set; }
        public string mensaje { get; set; }
        public string Respuesta { get; set; }
    
        public virtual asesore asesore { get; set; }
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallesolicitud> detallesolicituds { get; set; }
        public virtual actividade actividade { get; set; }
    }
}
